name: dart_ping_ios
description: Add iOS support to dart_ping via plugin registration.
version: 1.0.0
homepage: https://github.com/point-source/dart_ping

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  dart_ping: ^6.1.0
  flutter_icmp_ping: ^3.0.1

dev_dependencies:
  flutter_lints: ^1.0.4
  test: ^1.14.4
